echo -----$AZURE_KEY_STORE_URI
#Launch Application
env AZURE_KEY_STORE_URI=$AZURE_KEY_STORE_URI AZURE_CLIENT_ID=$AZURE_CLIENT_ID AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET AZURE_TENANT_ID=$AZURE_TENANT_ID node bin/server.js